sylius_grid:
  grids:
    bitbag_admin_shipping_export:
      fields:
        weight:
          type: twig
          label: ikuzo.ui.shippingWeight
          path: .
          options:
            template: "@IkuzoSyliusColishipPlugin/ShippingExport/Grid/Field/shipmentWeight.html.twig"