sylius_grid:
  grids:
    bitbag_admin_shipping_export:
      fields:
        cn23:
          type: twig
          label: ikuzo.ui.cn23
          path: .
          options:
            template: "@IkuzoSyliusColishipPlugin/ShippingExport/Grid/Field/cn23.html.twig"
        weight:
          type: twig
          label: ikuzo.ui.shippingWeight
          path: .
          options:
            template: "@IkuzoSyliusColishipPlugin/ShippingExport/Grid/Field/shipmentWeight.html.twig"

sylius_resource:
  resources:
    bitbag.shipping_export:
      classes:
        controller: Ikuzo\SyliusColishipPlugin\Controller\ShippingExportController