ikuzo_admin_coliship_set_weight:
    path: /shipping-exports/set-weight/{id}
    controller: Ikuzo\SyliusColishipPlugin\Controller\ShippingExportWeightController::setWeight
    methods: ['GET', 'POST']

ikuzo_admin_coliship_export_cn23:
    path: /shipping-exports/export-cn23/{id}
    controller: Ikuzo\SyliusColishipPlugin\Controller\ShippingExportCn23Controller::export
    methods: ['GET', 'POST']